# Generated by Django 5.1.6 on 2025-04-17 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='url',
            field=models.URLField(default='https://cdn-icons-png.flaticon.com/512/263/263142.png'),
        ),
    ]
